version: "3.3"

services:
  apache:
    image: php:7-apache
    restart: "no"
    container_name: apache_1
    ports:
      - "80:80"
    volumes:
      - ../html:/var/www/html
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"